# Generated by Django 3.1.2 on 2020-11-09 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='deadline_date',
        ),
    ]
