# Generated by Django 3.1.2 on 2020-11-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_info', '0003_course_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deadline_time',
            field=models.TimeField(null=True),
        ),
    ]
