# Generated by Django 3.1.2 on 2020-11-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_info', '0008_auto_20201109_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='answer',
            field=models.FileField(upload_to='assignments/None'),
        ),
    ]
