# Generated by Django 3.1.2 on 2020-11-12 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment_info', '0010_auto_20201112_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='assignment_info.course'),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
